server:
  port: 8081
  servlet:
    context-path: "/ead-authuser/"

spring:
  application:
    name: ead-authuser-service
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: password
  datasource:
    url: jdbc:postgresql://localhost:5433/ead-authuser
    username: administrator
    password: administrator
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  output:
    ansi:
      enabled: ALWAYS
ead:
  api:
    url:
      course: "http://ead-course-service/ead-course"
  broker:
    exchange:
      userEvent: ead.userevent

resilience4j:
  circuitbreaker:
    instances:
      circuitBreakerInstance:
        slidingWindowSize: 20
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowType: TIME_BASED
        minimumNumberOfCalls: 2
        waitDurationInOpenState: 30s
        failureRateThreshold: 60

  retry:
    retry-aspect-order: 2
    instances:
      retryInstance:
        max-attempts: 3
        wait-duration: 5s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - org.springframework.web.client.RestClientException
          - org.springframework.web.client.ResourceAccessException

management:
  endpoints:
    web:
      exposure:
        include: "*"

authuser:
  refreshscope:
    name: "Name"
